#!/bin/bash

export MAX_ROWS=200000000
export RUN_MINUTES=2
export NUM_ROWS_PER_INSERT=1000
export MAX_INSERTS_PER_SECOND=9999999

export NUM_INSERTS_PER_FEEDBACK=-1
export NUM_SECONDS_PER_FEEDBACK=10

export MYSQL_DATABASE=iibench
export BENCHMARK_NUMBER=999

export NUM_LOADER_THREADS=4
export NUM_CHAR_FIELDS=0
export LENGTH_CHAR_FIELDS=512
export PERCENT_COMPRESSIBLE=25

export QUERIES_PER_INTERVAL=0
export QUERY_INTERVAL_SECONDS=30
export QUERY_LIMIT=1000
export QUERY_NUM_ROWS_BEGIN=100000000

export NUM_SECONDARY_INDEXES=3

export TOKUDB_DIRECTIO_CACHE=2G
export INNODB_CACHE=2G
export INNODB_KEY_BLOCK_SIZE=0


mysql-clean


# TokuDB - MySQL 5.5
export TARBALL=blank-toku753-mysql-5.5.40
export MYSQL_STORAGE_ENGINE=tokudb
export DIRECTIO=Y
export TOKUDB_READ_BLOCK_SIZE=64K
export TOKUDB_COMPRESSION=quicklz
#for dpi in 100 200 500 1000; do
#    export NUM_ROWS_PER_INSERT=${dpi}
#    export BENCH_ID=${TARBALL}-${TOKUDB_COMPRESSION}-${NUM_SECONDARY_INDEXES}-${NUM_CHAR_FIELDS}-${LENGTH_CHAR_FIELDS}-${PERCENT_COMPRESSIBLE}-${NUM_ROWS_PER_INSERT}
#    ./doit.bash
#    mysql-clean
#done
export NUM_ROWS_PER_INSERT=200
export BENCH_ID=${TARBALL}-${TOKUDB_COMPRESSION}-${NUM_SECONDARY_INDEXES}-${NUM_CHAR_FIELDS}-${LENGTH_CHAR_FIELDS}-${PERCENT_COMPRESSIBLE}-${NUM_ROWS_PER_INSERT}
#./doit.bash
mysql-clean


# InnoDB - MySQL 5.5
#for keyBlockSize in 0 1 2 4 8 16; do
for keyBlockSize in 0; do
    export INNODB_KEY_BLOCK_SIZE=$keyBlockSize
    export TARBALL=blank-mysql5539
    export MYSQL_STORAGE_ENGINE=innodb
    export BENCH_ID=${TARBALL}-${INNODB_KEY_BLOCK_SIZE}-${NUM_SECONDARY_INDEXES}-${NUM_CHAR_FIELDS}-${LENGTH_CHAR_FIELDS}-${PERCENT_COMPRESSIBLE}
#    ./doit.bash
    mysql-clean
done


# InnoDB - MySQL 5.6
#for keyBlockSize in 0 1 2 4 8 16; do
for keyBlockSize in 0 8; do
    export INNODB_KEY_BLOCK_SIZE=$keyBlockSize
    export TARBALL=blank-mysql5620
    export MYSQL_STORAGE_ENGINE=innodb
    export BENCH_ID=${TARBALL}-${INNODB_KEY_BLOCK_SIZE}-${NUM_SECONDARY_INDEXES}-${NUM_CHAR_FIELDS}-${LENGTH_CHAR_FIELDS}-${PERCENT_COMPRESSIBLE}
#    ./doit.bash
    mysql-clean
done



# TokuDB - MySQL 5.5
export TARBALL=blank-toku753-mysql-5.5.40
export MYSQL_STORAGE_ENGINE=tokudb
export TOKUDB_DIRECTIO_CACHE=2G
export DIRECTIO=Y
export TOKUDB_COMPRESSION=quicklz
export NUM_ROWS_PER_INSERT=250
export RUN_MINUTES=30
for tokudbReadBlockSize in 16K 32K 64K; do
    for tokudbBlockSize in 256K 512K 1M 4M; do
        export TOKUDB_READ_BLOCK_SIZE=${tokudbReadBlockSize}
        export TOKUDB_BLOCK_SIZE=${tokudbBlockSize}
        export BENCH_ID=${TARBALL}-${TOKUDB_COMPRESSION}-${NUM_SECONDARY_INDEXES}-${NUM_CHAR_FIELDS}-${LENGTH_CHAR_FIELDS}-${PERCENT_COMPRESSIBLE}-${NUM_ROWS_PER_INSERT}-${TOKUDB_READ_BLOCK_SIZE}-${TOKUDB_BLOCK_SIZE}
        ./doit.bash
        mysql-clean
    done
done
