#!/bin/bash

export MAX_ROWS=100000000
export RUN_MINUTES=999999
export NUM_ROWS_PER_INSERT=250
export MAX_INSERTS_PER_SECOND=9999999

export NUM_INSERTS_PER_FEEDBACK=-1
export NUM_SECONDS_PER_FEEDBACK=5

export MYSQL_DATABASE=iibench
export BENCHMARK_NUMBER=999

export NUM_LOADER_THREADS=4
export NUM_CHAR_FIELDS=1
export LENGTH_CHAR_FIELDS=1024
export PERCENT_COMPRESSIBLE=75

export QUERIES_PER_INTERVAL=0
export QUERY_INTERVAL_SECONDS=30
export QUERY_LIMIT=1000
export QUERY_NUM_ROWS_BEGIN=100000000

export NUM_SECONDARY_INDEXES=0

#export TOKUDB_DIRECTIO_CACHE=2G
#export INNODB_CACHE=2G
export INNODB_KEY_BLOCK_SIZE=0
#export DIRECTIO=Y
#export TOKUDB_READ_BLOCK_SIZE=64K
#export TOKUDB_COMPRESSION=quicklz

export SKIP_DB_CREATE=Y
export SHUTDOWN_MYSQL=N
export SCP_FILES=N

export MYSQL_SERVER=localhost
export MYSQL_ROOT_USER=root
export MYSQL_ROOT_PASSWORD=""
export MYSQL_USER=tmc
export MYSQL_PASSWORD=tmc
mysql-rr
mysql-user


# TokuDB - MySQL 5.5
export TARBALL=blank-toku753-mysql-5.5.40
export MYSQL_STORAGE_ENGINE=tokudb
export BENCH_ID=${TARBALL}-${TOKUDB_COMPRESSION}-${NUM_SECONDARY_INDEXES}-${NUM_CHAR_FIELDS}-${LENGTH_CHAR_FIELDS}-${PERCENT_COMPRESSIBLE}-${NUM_ROWS_PER_INSERT}
./doit.bash
