#!/bin/bash

export NUM_COLLECTIONS=12
#export NUM_DOCUMENTS_PER_COLLECTION=10000000
export NUM_DOCUMENTS_PER_COLLECTION=1000000
export DB_NAME=sbtest
export NUM_WRITER_THREADS=15
export NUM_SECONDS_PER_FEEDBACK=10
export BENCHMARK_TSV=benchmark.log.tsv
export SYSBENCH_READ_ONLY=N
export RUN_TIME_SECONDS=7200
export SYSBENCH_RANGE_SIZE=100
export SYSBENCH_POINT_SELECTS=10
export SYSBENCH_SIMPLE_RANGES=1
export SYSBENCH_SUM_RANGES=1
export SYSBENCH_ORDER_RANGES=1
export SYSBENCH_DISTINCT_RANGES=1
export SYSBENCH_INDEX_UPDATES=1
export SYSBENCH_NON_INDEX_UPDATES=1

# FSYNC_SAFE, NONE, NORMAL, REPLICAS_SAFE, SAFE
export WRITE_CONCERN=SAFE

export MAX_TPS=29
export MONGO_SERVER=localhost
export MONGO_PORT=30011

LOG_NAME=benchmark.log
rm -f ${LOG_NAME}

ant clean default
ant execute | tee -a ${LOG_NAME}
